# static values for: Ports, paths and more
DEFAULT_HOST = "0.0.0.0"
USERNAME_FILE = "~/.localchat_user"
SETTINGS_FILE = "~/.localchat_settings.json"
DEFAULT_PORT = 51121
DISCOVERY_PORT = 51111
UDP_BROADCAST_PORT = 51122
BUFFER_SIZE = 4096
ENCODING = "utf-8"
DEFAULT_MAX_CLIENTS = 16
HARD_MAX_CLIENTS = 128

# default Settings
DEFAULT_HOST_SERVER_PORT = DEFAULT_PORT
DEFAULT_NAME_COLOR = "white"
DEFAULT_SHOW_TIMESTAMPS = False
DEFAULT_SHOW_JOIN_LEAVE_NOTIFICATIONS = True
DEFAULT_CHAT_EXPORT_PATH = "~/Downloads"
DEFAULT_ENABLE_COMMAND_SUGGESTIONS = True
DEFAULT_THEME = "classic"