# size limits for data packages, time limits, size limits for user controlled data like names and messages
MAX_USER_NAME_LENGTH = 512
MAX_CHAT_NAME_LENGTH = 1024
MAX_CHAT_SERIALIZATION_METHOD_NAME_LENGTH = 256
# deprecated
MAX_CHAT_SERIALIZATION_METHODE_NAME_LENGTH = MAX_CHAT_SERIALIZATION_METHOD_NAME_LENGTH
MAX_MESSAGE_LENGTH = 64 * 1024
